### ISSUE TITLE
Not parsing HRM programs with dereferencing

### ISSUE THREAD

**Issue by nrkn** [sixlettervariables/hrm-grammar#1]
I saw that you had a commit that added it but doesn't seem to work correctly yet?

Tested with 1.6.0:

https://gist.github.com/nrkn/e956ccf2d7e610736dc1

**Comment by sixlettervariables** [comment]
Yeah the extended grammar seems to fail, working on it now actually.

On Mon, Oct 26, 2015 at 10:54 PM, Nik Coughlin notifications@github.com
wrote:

> I saw that you had a commit that added it but doesn't seem to work
> correctly yet?
> 
> Tested with 1.6.0:
> 
> https://gist.github.com/nrkn/e956ccf2d7e610736dc1
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sixlettervariables/hrm-grammar/issues/1.

## 

Christopher A. Watford
christopher.watford@gmail.com

**Comment by nrkn** [comment]
Cool :) I tried to have a crack at it but it turns out I've forgotten most of what I knew about peg.js, it's been a while :/

**Comment by sixlettervariables** [comment]
It was due to a change in the IdentifierName production. I switched away from the Kleene star in the strict grammar, but forgot to in the extended grammar.

**Comment by nrkn** [comment]
Cool, it works with the hrm file in the fixtures folder, but I still get an error with the file I linked to in the gist?

Was pretty excited when I ran it against the fixture file and saw an AST pop out though!

**Comment by sixlettervariables** [comment]
Sorry, didn't commit+publish.

On Mon, Oct 26, 2015 at 11:21 PM, Nik Coughlin notifications@github.com
wrote:

> Cool, it works with the hrm file in the fixtures folder, but I still get
> an error with the file I linked to in the gist?
> 
> Was pretty excited when I ran it against the fixture file and saw an AST
> pop out though!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sixlettervariables/hrm-grammar/issues/1#issuecomment-151360908
> .

## 

Christopher A. Watford
christopher.watford@gmail.com
